// Copies the ABIs the site uses from the Foundry build (../contracts/out) into src/abi/<Name>.ts as `as const`
// arrays, so viem infers argument and return types. Run after `forge build` when an interface changes: npm run abis
import { readFileSync, writeFileSync } from 'node:fs';
const OUT = new URL('../../contracts/out/', import.meta.url);
const NAMES = ['PadLens', 'PadRouter', 'BondingCurve', 'PadHook', 'PadFactory', 'CreatorVault', 'PadToken', 'PadConfig', 'SocialRegistry', 'IntegratorVault', 'PadSale', 'PadMarketHook', 'MarketController', 'AirdropDistributor', 'PondPadToken', 'PoolSwapTest', 'StakedPONDPAD', 'RewardDripper', 'PadBuyer', 'FeeSplitter', 'WorkerFund', 'GrowthFund', 'SwarmBudget', 'AttestationVerifier', 'CTOModule', 'VersionRegistry', 'TeamVesting', 'TimelockController'];
const index = [];
for (const n of NAMES) {
  const { abi } = JSON.parse(readFileSync(new URL(`${n}.sol/${n}.json`, OUT)));
  writeFileSync(new URL(`../src/abi/${n}.ts`, import.meta.url), `// Generated by scripts/abis.mjs from contracts/out. Do not edit.\nexport const ${n}Abi = ${JSON.stringify(abi)} as const;\n`);
  index.push(`export { ${n}Abi } from './${n}';`);
}
writeFileSync(new URL('../src/abi/index.ts', import.meta.url), index.join('\n') + "\nexport { QuoterAbi } from './Quoter';\n");
console.log(`wrote ${NAMES.length} ABIs`);
