"""Generates src/StakedPONDPAD.sol and src/RewardDripper.sol from POOL4's verified sources in upstream/.
Run from launchpad/contracts: python3 upstream/make_staking.py. Edit this script, not the outputs."""


def make(src, dst, edits, banned):
    s = open(src).read()
    for old, new, *cnt in edits:
        n = s.count(old)
        assert n == (cnt[0] if cnt else 1), (dst, old[:80], n)
        s = s.replace(old, new)
    code = '\n'.join(l.split('//')[0] for l in s.splitlines())
    for b in banned:
        assert b not in code, (dst, b)
    open(dst, 'w').write(s)


POWERS = '''
    // ─────────────────────────────── PondPad: limited, expiring powers (D-42) ───────────────────────────────

    /// @notice PondPad: every owner power stops working at this time (12 months after launch), as if renounced.
    uint256 public immutable powersExpireAt;

    error PowersExpired();

    modifier onlyOwnerActive() {
        _checkOwner();
        if (block.timestamp >= powersExpireAt) revert PowersExpired();
        _;
    }
'''

# ------------------------------------------------------------------ StakedPONDPAD
make('upstream/StakedIMD.sol', 'src/StakedPONDPAD.sol', [
    ('pragma solidity ^0.8.24;', 'pragma solidity 0.8.26;'),
    ('/// @notice Single-asset, autocompounding IMD staking vault.', '''/// @notice PondPad: sPONDPAD, a fork of POOL4's StakedIMD (MIT, 0x9efa934d9fad4ae28c998a40195646b965a97247; original in
/// `upstream/StakedIMD.sol`, regenerated by `upstream/make_staking.py`). Asset is $PONDPAD instead of IMD. Owner
/// powers are narrowed (D-42): the owner (7-day timelock) can pause for at most 3 days at a time, with 4 days
/// unpaused between pauses; `rescueERC20` can never touch the staked $PONDPAD; and every power expires
/// `powersExpireAt` (12 months after launch). Everything else is unchanged. Upstream doc follows ("IMD" = the asset).
///
/// Single-asset, autocompounding IMD staking vault.'''),
    ('contract StakedIMD is ERC4626, Ownable {', 'contract StakedPONDPAD is ERC4626, Ownable {'),
    ('''    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. Owner-controlled.
    bool public paused;
''', '''    /// @notice PondPad: a pause lasts until this time (at most `MAX_PAUSE` after it starts).
    uint256 public pausedUntil;
    /// @notice PondPad: a new pause may start only from this time (`PAUSE_COOLDOWN` after the last one ended).
    uint256 public nextPauseAllowedAt;
    uint256 public constant MAX_PAUSE = 3 days;
    uint256 public constant PAUSE_COOLDOWN = 4 days;
''' + POWERS),
    ('''    error SameBlockRedeem();
''', '''    error SameBlockRedeem();
    error CannotRescueStake();
    error PauseCooldown();
'''),
    ('''    constructor(address asset_, address owner_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        _initializeOwner(owner_);
    }''', '''    constructor(address asset_, address owner_, uint256 powersExpireAt_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        powersExpireAt = powersExpireAt_;
        _initializeOwner(owner_);
    }

    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. PondPad: time-limited.
    function paused() public view returns (bool) {
        return block.timestamp < pausedUntil;
    }'''),
    ('''        return "Staked IMD";''', '''        return "Staked PondPad";'''),
    ('''        return "sIMD";''', '''        return "sPONDPAD";'''),
    ('if (paused) revert EnforcedPause();', 'if (paused()) revert EnforcedPause();'),
    ('return paused ? 0 : super.maxDeposit(to);', 'return paused() ? 0 : super.maxDeposit(to);'),
    ('return paused ? 0 : super.maxMint(to);', 'return paused() ? 0 : super.maxMint(to);'),
    ('if (paused || block.number == lastDepositBlock[owner]) return 0;', 'if (paused() || block.number == lastDepositBlock[owner]) return 0;', 2),
    ('''    /// @notice Owner emergency stop / resume.
    function setPaused(bool paused_) external onlyOwner {
        paused = paused_;
        emit PauseSet(paused_);
    }''', '''    /// @notice Owner emergency stop / resume. PondPad: a stop lasts at most 3 days and the next one can start only
    /// 4 days after it ended, so funds are never frozen for long; resuming early is always allowed.
    function setPaused(bool paused_) external onlyOwnerActive {
        if (paused_) {
            if (paused() || block.timestamp < nextPauseAllowedAt) revert PauseCooldown();
            pausedUntil = block.timestamp + MAX_PAUSE;
        } else {
            if (paused()) pausedUntil = block.timestamp;
        }
        nextPauseAllowedAt = (paused_ ? block.timestamp + MAX_PAUSE : block.timestamp) + PAUSE_COOLDOWN;
        emit PauseSet(paused_);
    }'''),
    ('''    /// @notice Owner sweeps an ERC20 balance — INCLUDING the staked IMD — to `to`. Trusted power,
    /// removed on `renounceOwnership()`.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwner {''', '''    /// @notice Owner sweeps a stray ERC20 balance to `to`. PondPad: never the staked asset.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == _asset) revert CannotRescueStake();'''),
    ('function rescueETH(address to, uint256 amount) external onlyOwner {', 'function rescueETH(address to, uint256 amount) external onlyOwnerActive {'),
    ('if (paused) revert RenounceWhilePaused();', 'if (paused()) revert RenounceWhilePaused();'),
], ['bool public paused', 'paused ?', 'external onlyOwner {'])

# ------------------------------------------------------------------ RewardDripper
make('upstream/RewardDripper.sol', 'src/RewardDripper.sol', [
    ('pragma solidity ^0.8.24;', 'pragma solidity 0.8.26;'),
    ('/// @notice Smooths the market\'s lumpy 10% reward share into a bounded stream for the staking vault.', '''/// @notice PondPad: a fork of POOL4's RewardDripper (MIT, 0xe6D3De6daEAf327fCA42745f1998FcD989e00884; original in
/// `upstream/RewardDripper.sol`, regenerated by `upstream/make_staking.py`). The streamed asset is $PONDPAD (the
/// variable keeps its upstream name `imd`). Inflows: 15% of the market's trims, PadBuyer's purchases and the
/// stakers' share of $PONDPAD fees. Changes (D-42): the vault is fixed at deploy (no `setVault`); `rescueERC20`
/// can never touch the reward buffer; every setter keeps the stream drainable (rate > 0, min drip within one
/// call's ceiling); all owner powers expire at `powersExpireAt` (12 months after launch), after which the stream
/// runs on its last settings forever. Upstream doc follows.
///
/// Smooths the market's lumpy 10% reward share into a bounded stream for the staking vault.'''),
    ('''    /// @notice The staking vault that receives the stream. A plain transfer raises its `totalAssets`.
    address public vault;''', '''    /// @notice The staking vault that receives the stream. A plain transfer raises its `totalAssets`.
    /// PondPad: immutable.
    address public immutable vault;'''),
    ('''    error VaultEmpty();
''', '''    error VaultEmpty();
    error CannotRescueRewards();
''' + POWERS),
    ('''        uint256 keeperReward_,
        uint256 minDripAmount_
    ) {''', '''        uint256 keeperReward_,
        uint256 minDripAmount_,
        uint256 powersExpireAt_
    ) {'''),
    ('''        if (keeperReward_ > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        imd = imd_;''', '''        if (keeperReward_ > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        // PondPad: start in a configuration that can always drain.
        if (dripRatePerSecond_ == 0 || minDripAmount_ > dripRatePerSecond_ * maxCatchupSeconds_) revert RenounceWouldFreeze();
        powersExpireAt = powersExpireAt_;
        imd = imd_;'''),
    ('''    function setVault(address vault_) external onlyOwner {
        if (vault_ == address(0)) revert ZeroAddress();
        vault = vault_;
        emit VaultSet(vault_);
    }

''', ''),
    ('''    function setDripRate(uint256 dripRatePerSecond_) external onlyOwner {
        if (dripRatePerSecond_ > MAX_RATE) revert RateTooHigh();''', '''    function setDripRate(uint256 dripRatePerSecond_) external onlyOwnerActive {
        if (dripRatePerSecond_ > MAX_RATE) revert RateTooHigh();
        if (dripRatePerSecond_ == 0 || minDripAmount > dripRatePerSecond_ * maxCatchupSeconds) revert RenounceWouldFreeze();'''),
    ('''    function setMaxCatchup(uint256 maxCatchupSeconds_) external onlyOwner {
        if (maxCatchupSeconds_ == 0 || maxCatchupSeconds_ > MAX_CATCHUP) revert CatchupTooHigh();''', '''    function setMaxCatchup(uint256 maxCatchupSeconds_) external onlyOwnerActive {
        if (maxCatchupSeconds_ == 0 || maxCatchupSeconds_ > MAX_CATCHUP) revert CatchupTooHigh();
        if (minDripAmount > dripRatePerSecond * maxCatchupSeconds_) revert RenounceWouldFreeze();'''),
    ('function setKeeperReward(uint256 keeperReward_) external onlyOwner {', 'function setKeeperReward(uint256 keeperReward_) external onlyOwnerActive {'),
    ('''    function setMinDripAmount(uint256 minDripAmount_) external onlyOwner {
        if (keeperReward > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();''', '''    function setMinDripAmount(uint256 minDripAmount_) external onlyOwnerActive {
        if (keeperReward > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        if (minDripAmount_ > dripRatePerSecond * maxCatchupSeconds) revert RenounceWouldFreeze();'''),
    ('''    /// @notice Owner sweeps a balance — including the reward IMD buffer — to `to`. Trusted power,
    /// removed on `renounceOwnership()`.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwner {''', '''    /// @notice Owner sweeps a stray balance to `to`. PondPad: never the reward buffer.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == imd) revert CannotRescueRewards();'''),
    ('function rescueETH(address to, uint256 amount) external onlyOwner {', 'function rescueETH(address to, uint256 amount) external onlyOwnerActive {'),
    ('''    event VaultSet(address indexed vault);
''', ''),
], ['external onlyOwner {', 'setVault'])
print('ok')
