"""Generates src/StakedPONDPAD.sol and src/RewardDripper.sol from POOL4's verified sources in upstream/.
Run from launchpad/contracts: python3 upstream/make_staking.py. Edit this script, not the outputs."""


def make(src, dst, edits, banned):
    s = open(src).read()
    for old, new, *cnt in edits:
        n = s.count(old)
        assert n == (cnt[0] if cnt else 1), (dst, old[:80], n)
        s = s.replace(old, new)
    code = '\n'.join(l.split('//')[0] for l in s.splitlines())
    for b in banned:
        assert b not in code, (dst, b)
    open(dst, 'w').write(s)


POWERS = '''
    // ─────────────────────────────── PondPad: limited, expiring powers (D-42) ───────────────────────────────

    /// @notice PondPad: every owner power stops working at this time (12 months after launch), as if renounced.
    uint256 public immutable powersExpireAt;

    error PowersExpired();

    modifier onlyOwnerActive() {
        _checkOwner();
        if (block.timestamp >= powersExpireAt) revert PowersExpired();
        _;
    }
'''

# ------------------------------------------------------------------ StakedPONDPAD
make('upstream/StakedIMD.sol', 'src/StakedPONDPAD.sol', [
    ('pragma solidity ^0.8.24;', 'pragma solidity 0.8.26;'),
    ('/// @notice Single-asset, autocompounding IMD staking vault.', '''/// @notice PondPad: sPONDPAD, a fork of POOL4's StakedIMD (MIT, 0x9efa934d9fad4ae28c998a40195646b965a97247; original in
/// `upstream/StakedIMD.sol`, regenerated by `upstream/make_staking.py`). Asset is $PONDPAD instead of IMD. Owner
/// powers are narrowed (D-42): the owner (7-day timelock) can pause for at most 3 days at a time, with 4 days
/// unpaused between pauses; `rescueERC20` can never touch the staked $PONDPAD; and every power expires
/// `powersExpireAt` (12 months after launch). Audit fixes: only the shares that arrived this block are held
/// (R1-A3-2); `totalAssets` is the vault's own count, not its raw balance, so a transfer into an empty vault can't
/// move the share price, and rewards are taken in only while at least one whole $PONDPAD is staked (R2-A3-1).
/// Upstream doc follows ("IMD" = the asset).
///
/// Single-asset, autocompounding IMD staking vault.'''),
    ('contract StakedIMD is ERC4626, Ownable {', 'contract StakedPONDPAD is ERC4626, Ownable {'),
    ('''    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. Owner-controlled.
    bool public paused;
''', '''    /// @notice PondPad: a pause lasts until this time (at most `MAX_PAUSE` after it starts).
    uint256 public pausedUntil;
    /// @notice PondPad: a new pause may start only from this time (`PAUSE_COOLDOWN` after the last one ended).
    uint256 public nextPauseAllowedAt;
    uint256 public constant MAX_PAUSE = 3 days;
    uint256 public constant PAUSE_COOLDOWN = 4 days;
''' + POWERS),
    ('''    error SameBlockRedeem();
''', '''    error SameBlockRedeem();
    error CannotRescueStake();
    error PauseCooldown();
    error RewardsClosed();

    event RewardsSynced(uint256 amount, uint256 trackedAssets);
'''),
    ('''    constructor(address asset_, address owner_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        _initializeOwner(owner_);
    }''', '''    constructor(address asset_, address owner_, uint256 powersExpireAt_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        powersExpireAt = powersExpireAt_;
        _initializeOwner(owner_);
    }

    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. PondPad: time-limited.
    function paused() public view returns (bool) {
        return block.timestamp < pausedUntil;
    }'''),
    ('''        return "Staked IMD";''', '''        return "Staked PondPad";'''),
    ('''        return "sIMD";''', '''        return "sPONDPAD";'''),
    ('if (paused) revert EnforcedPause();', 'if (paused()) revert EnforcedPause();'),
    ('return paused ? 0 : super.maxDeposit(to);', 'return paused() ? 0 : super.maxDeposit(to);'),
    ('return paused ? 0 : super.maxMint(to);', 'return paused() ? 0 : super.maxMint(to);'),
    ("""    /// @notice Block of each holder's most recent share-increasing action, for the one-block hold.
    mapping(address => uint256) public lastDepositBlock;
""", """    /// @notice Block of each holder's most recent share-increasing action, for the one-block hold.
    mapping(address => uint256) public lastDepositBlock;
    /// @notice PondPad (audit R1-A3-2): shares that reached each holder in block `lastDepositBlock`; only these
    /// are held, not the whole balance.
    mapping(address => uint256) public heldShares;

    /// @notice PondPad (audit R2-A3-1): the staked $PONDPAD the vault counts (`totalAssets`). Upstream counted its
    /// raw balance, so a dust transfer into the empty vault fixed a share price at which no stake could ever reach
    /// the dripper's minimum. Deposits add, withdrawals subtract, and $PONDPAD that arrives by plain transfer (the
    /// dripper's drips) counts only once `syncRewards()` takes it in, which works only while rewards are open.
    uint256 public trackedAssets;
    /// @notice PondPad: rewards are open while at least this many shares AND this much $PONDPAD are staked. One whole
    /// $PONDPAD at the starting price; the 1e6 virtual shares then get at most 1e-12 of a drip (R1-A3-1).
    uint256 public constant MIN_REWARD_SHARES = 1e18;
    uint256 public constant MIN_REWARD_ASSETS = 1e18;
    /// @notice PondPad (audit R2-A3-3): when rewards last opened (0 while closed). The dripper releases nothing
    /// for time the vault was closed, so the first staker can't collect a window banked before it.
    uint256 public rewardsOpenSince;
"""),
    ("""        if (block.number == lastDepositBlock[owner]) revert SameBlockRedeem();
        super._withdraw(by, to, owner, assets, shares);""", """        if (shares > _unheldShares(owner)) revert SameBlockRedeem();
        super._withdraw(by, to, owner, assets, shares);"""),
    ("""    /// @dev The one-block anti-JIT hold must travel WITH the shares""", """    /// @dev PondPad (audit R1-A3-2): upstream held the holder's WHOLE balance for the block after any share
    /// arrived, so anyone could block a staker's exit with `deposit(1 wei, victim)` or a 1-share transfer,
    /// every Ethereum block (D-65). Here only the shares that arrived in the current block are held: a mint
    /// holds the minted shares; a transfer moves the sender's unheld shares first and carries any held ones
    /// with it. A flash-loaned deposit is still fully held wherever it goes; stranger dust holds only the dust.
    function _heldShares(address owner) internal view returns (uint256) {
        return lastDepositBlock[owner] == block.number ? heldShares[owner] : 0;
    }

    function _unheldShares(address owner) internal view returns (uint256) {
        uint256 bal = balanceOf(owner);
        uint256 held = _heldShares(owner);
        return bal > held ? bal - held : 0;
    }

    function _hold(address to, uint256 shares) internal {
        if (lastDepositBlock[to] != block.number) {
            lastDepositBlock[to] = block.number;
            heldShares[to] = shares;
        } else {
            heldShares[to] += shares;
        }
    }

    /// @dev Upstream: the one-block anti-JIT hold must travel WITH the shares"""),
    ("""        if (amount == 0 || to == address(0)) return;
        if (from == address(0)) {
            lastDepositBlock[to] = block.number; // mint (deposit)
        } else if (lastDepositBlock[from] > lastDepositBlock[to]) {
            lastDepositBlock[to] = lastDepositBlock[from]; // transfer inherits the sender's hold
        }""", """        // PondPad (audit R3-A3-5): burns and transfers to address(0) also go through the bookkeeping, so the sender's
        // held count never stays above its balance (a redeem only burns unheld shares, so it changes nothing there).
        if (amount == 0) return;
        if (from == address(0)) {
            _hold(to, amount); // mint (deposit): the new shares are held
        } else {
            // transfer: unheld shares leave first; any held part travels with the shares (none to address(0))
            uint256 held = _heldShares(from);
            uint256 unheld = balanceOf(from) - held;
            if (amount > unheld) {
                uint256 moved = amount - unheld;
                heldShares[from] = held - moved;
                if (to != address(0)) _hold(to, moved);
            }
        }"""),
    ("""    function maxWithdraw(address owner) public view override returns (uint256) {
        if (paused || block.number == lastDepositBlock[owner]) return 0;
        return super.maxWithdraw(owner);
    }

    function maxRedeem(address owner) public view override returns (uint256) {
        if (paused || block.number == lastDepositBlock[owner]) return 0;
        return super.maxRedeem(owner);
    }""", """    function maxWithdraw(address owner) public view override returns (uint256) {
        if (paused()) return 0;
        return convertToAssets(_unheldShares(owner)); // PondPad: held shares only (R1-A3-2)
    }

    function maxRedeem(address owner) public view override returns (uint256) {
        if (paused()) return 0;
        return _unheldShares(owner); // PondPad: held shares only (R1-A3-2)
    }"""),
    ('''    /// @notice Owner emergency stop / resume.
    function setPaused(bool paused_) external onlyOwner {
        paused = paused_;
        emit PauseSet(paused_);
    }''', '''    /// @notice Owner emergency stop / resume. PondPad: a stop lasts at most 3 days and the next one can start only
    /// 4 days after it ended, so funds are never frozen for long; resuming early is always allowed.
    function setPaused(bool paused_) external onlyOwnerActive {
        if (paused_) {
            if (paused() || block.timestamp < nextPauseAllowedAt) revert PauseCooldown();
            // A pause never outlives the owner's powers (audit R1-A3-7): nobody could lift it after expiry.
            uint256 until = block.timestamp + MAX_PAUSE;
            pausedUntil = until < powersExpireAt ? until : powersExpireAt;
        } else {
            if (paused()) pausedUntil = block.timestamp;
        }
        nextPauseAllowedAt = (paused_ ? block.timestamp + MAX_PAUSE : block.timestamp) + PAUSE_COOLDOWN;
        emit PauseSet(paused_);
    }'''),
    ('''    /// @notice Owner sweeps an ERC20 balance — INCLUDING the staked IMD — to `to`. Trusted power,
    /// removed on `renounceOwnership()`.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwner {''', '''    /// @notice Owner sweeps a stray ERC20 balance to `to`. PondPad: never the staked asset.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == _asset) revert CannotRescueStake();'''),
    ('function rescueETH(address to, uint256 amount) external onlyOwner {', 'function rescueETH(address to, uint256 amount) external onlyOwnerActive {'),
    ('if (paused) revert RenounceWhilePaused();', 'if (paused()) revert RenounceWhilePaused();'),
    # PondPad (audit R2-A3-1, R2-A3-3): tracked assets, rewards intake only while open.
    ("""    function _decimalsOffset() internal pure override returns (uint8) {
        return 6;
    }
""", """    function _decimalsOffset() internal pure override returns (uint8) {
        return 6;
    }

    /// @dev PondPad (audit R2-A3-1): the vault's own count, never its raw balance. With no shares left the price
    /// restarts (any rounding residue goes to the next staker).
    function totalAssets() public view override returns (uint256) {
        return totalSupply() == 0 ? 0 : trackedAssets;
    }

    /// @notice PondPad (audit R2-A3-1): takes $PONDPAD that reached the vault by plain transfer (the dripper's drips,
    /// or a stray transfer) into `totalAssets`, raising every share's value. Permissionless, and only while rewards
    /// are open, so nothing sent to an empty or dust-only vault can ever move the share price.
    function syncRewards() external returns (uint256 amount) {
        if (rewardsOpenSince == 0) revert RewardsClosed();
        uint256 bal = SafeTransferLib.balanceOf(_asset, address(this));
        amount = bal - trackedAssets;
        trackedAssets = bal;
        emit RewardsSynced(amount, bal);
    }

    /// @dev PondPad (audit R2-A3-3): opens rewards when the stake first reaches the minimum, closes them below it.
    function _updateRewardsOpen() internal {
        if (totalSupply() < MIN_REWARD_SHARES || trackedAssets < MIN_REWARD_ASSETS) rewardsOpenSince = 0;
        else if (rewardsOpenSince == 0) rewardsOpenSince = block.timestamp;
    }
"""),
    ("""        super._deposit(by, to, assets, shares);
    }""", """        super._deposit(by, to, assets, shares);
        trackedAssets += assets; // PondPad (R2-A3-1)
        _updateRewardsOpen();
    }"""),
    ("""        if (shares > _unheldShares(owner)) revert SameBlockRedeem();
        super._withdraw(by, to, owner, assets, shares);""", """        if (shares > _unheldShares(owner)) revert SameBlockRedeem();
        trackedAssets -= assets; // PondPad (R2-A3-1)
        super._withdraw(by, to, owner, assets, shares);
        _updateRewardsOpen();"""),
    # PondPad (audit R2-A3-5): an over-balance transfer reverts with Solady's own error, not an underflow here.
    ("""            uint256 held = _heldShares(from);
            uint256 unheld = balanceOf(from) - held;""", """            uint256 bal = balanceOf(from);
            if (amount > bal) return; // Solady then reverts InsufficientBalance() (audit R2-A3-5)
            uint256 held = _heldShares(from);
            uint256 unheld = bal - held;"""),
    # PondPad (audits R3-A2-2 / R3-A4-4): the owner (the 7-day timelock) is fixed; the powers end at powersExpireAt.
    ('import {Ownable} from "solady/auth/Ownable.sol";', 'import {FixedOwnable} from "./FixedOwnable.sol";'),
    ('contract StakedPONDPAD is ERC4626, Ownable {', 'contract StakedPONDPAD is ERC4626, FixedOwnable {'),
    ("""    /// @dev Block the footgun of renouncing while paused, which would freeze the vault forever.
    function renounceOwnership() public payable override onlyOwner {
        if (paused()) revert RenounceWhilePaused();
        super.renounceOwnership();
    }""", """    // PondPad (audits R3-A2-2 / R3-A4-4): the owner can't renounce, transfer or hand over ownership
    // (FixedOwnable); its powers end at `powersExpireAt` instead, which can't leave the vault paused."""),
], ['bool public paused', 'paused ?', 'external onlyOwner {', 'is ERC4626, Ownable'])

# ------------------------------------------------------------------ RewardDripper
make('upstream/RewardDripper.sol', 'src/RewardDripper.sol', [
    ('pragma solidity ^0.8.24;', 'pragma solidity 0.8.26;'),
    ("/// @notice Smooths the market's lumpy 10% reward share into a bounded stream for the staking vault.", """/// @notice PondPad: a fork of POOL4's RewardDripper (MIT, 0xe6D3De6daEAf327fCA42745f1998FcD989e00884; original in
/// `upstream/RewardDripper.sol`, regenerated by `upstream/make_staking.py`). The streamed asset is $PONDPAD (the
/// variable keeps its upstream name `imd`). Inflows: 15% of the market's trims, PadBuyer's purchases and the
/// stakers' share of $PONDPAD fees. Changes:
///   - Self-adjusting release (D-44): instead of a fixed `dripRatePerSecond`, each drip releases
///     `buffer * elapsed / smoothingPeriod` (elapsed capped at `maxCatchupSeconds`), so the waiting rewards pay out
///     smoothly over about `smoothingPeriod` (default 7 days: ~0.6% of the buffer per hour) whatever the volume or
///     price. After a full catch-up window, a drip releases at least `min(minDripAmount, buffer / 7)` (audit
///     R3-A3-1), so small buffers keep draining without breaking the 1/7 bound; one below `minDripAmount` pays no
///     keeper tip, and a remainder under one whole $PONDPAD is swept in full.
///   - Drips wait until the vault is open for rewards (at least one whole $PONDPAD staked, audit R1-A3-1 /
///     R2-A3-1); time the vault was closed is forfeited, not banked (R2-A3-3). Each drip is taken in by the vault's
///     `syncRewards()`.
///   - Bounds (audit R2-A3-2, R2-A3-4, R1-A3-8, R3-A3-1): `1 hour <= maxCatchupSeconds <= smoothingPeriod / 7` and
///     the floor capped at 1/7 of the buffer, so one drip releases at most 1/7 of the buffer (or a remainder under
///     one $PONDPAD) and the floor fires at most hourly; `minDripAmount <= 100,000 $PONDPAD`.
///   - D-42: the vault is fixed at deploy (no `setVault`); `rescueERC20` can never touch the reward buffer; all
///     owner powers expire at `powersExpireAt` (12 months after launch).
/// Upstream doc follows; its "rate" wording describes the original fixed-rate formula.
///
/// Smooths the market's lumpy 10% reward share into a bounded stream for the staking vault."""),
    ("""    /// @notice The staking vault that receives the stream. A plain transfer raises its `totalAssets`.
    address public vault;
    /// @notice Sustained ceiling on throughput to the vault, in IMD wei per second.
    uint256 public dripRatePerSecond;""", """    /// @notice The staking vault that receives the stream. A plain transfer raises its `totalAssets`.
    /// PondPad: immutable.
    address public immutable vault;
    /// @notice PondPad: the waiting rewards are released over about this long (share per second = 1 / period).
    uint256 public smoothingPeriod;"""),
    ("""    uint256 internal constant MAX_CATCHUP = 30 days;
    uint256 internal constant MAX_RATE = type(uint128).max;""", """    uint256 internal constant MAX_CATCHUP = 30 days;
    uint256 public constant MIN_SMOOTHING = 1 days; // PondPad
    uint256 public constant MAX_SMOOTHING = 30 days; // PondPad
    /// @notice PondPad (audit R2-A3-4): a catch-up window of at least an hour, so the `minDripAmount` floor can't
    /// fire every second.
    uint256 public constant MIN_CATCHUP = 1 hours;
    /// @notice PondPad (audit R2-A3-2): `maxCatchupSeconds <= smoothingPeriod / 7`: one drip releases at most 1/7
    /// of the buffer.
    uint256 public constant CATCHUP_DIVISOR = 7;
    /// @notice PondPad (audit R1-A3-8): a larger floor could stall the stream, then release the buffer at once.
    uint256 public constant MAX_MIN_DRIP = 100_000e18;
    /// @notice PondPad (audit R3-A3-1): after a full window, a remainder under this is swept in full, so a buffer
    /// draining at 1/7 per window still empties.
    uint256 public constant DUST_SWEEP = 1e18;"""),
    ("""    event VaultSet(address indexed vault);
    event DripRateSet(uint256 dripRatePerSecond);""", """    event SmoothingPeriodSet(uint256 smoothingPeriod);"""),
    ("""    error RateTooHigh();""", """    error InvalidSmoothing();
    error CatchupTooLow();
    error MinDripTooHigh();"""),
    ("""    error VaultEmpty();
""", """    error VaultEmpty();
    error CannotRescueRewards();
""" + POWERS),
    ("""        address owner_,
        uint256 dripRatePerSecond_,
        uint256 maxCatchupSeconds_,
        uint256 keeperReward_,
        uint256 minDripAmount_
    ) {""", """        address owner_,
        uint256 smoothingPeriod_,
        uint256 maxCatchupSeconds_,
        uint256 keeperReward_,
        uint256 minDripAmount_,
        uint256 powersExpireAt_
    ) {"""),
    ("""        if (dripRatePerSecond_ > MAX_RATE) revert RateTooHigh();
        if (maxCatchupSeconds_ == 0 || maxCatchupSeconds_ > MAX_CATCHUP) revert CatchupTooHigh();
        if (keeperReward_ > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        imd = imd_;
        vault = vault_;
        dripRatePerSecond = dripRatePerSecond_;""", """        if (smoothingPeriod_ < MIN_SMOOTHING || smoothingPeriod_ > MAX_SMOOTHING) revert InvalidSmoothing();
        if (maxCatchupSeconds_ < MIN_CATCHUP) revert CatchupTooLow();
        if (maxCatchupSeconds_ > smoothingPeriod_ / CATCHUP_DIVISOR) revert CatchupTooHigh();
        if (minDripAmount_ > MAX_MIN_DRIP) revert MinDripTooHigh();
        if (keeperReward_ > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        powersExpireAt = powersExpireAt_;
        imd = imd_;
        vault = vault_;
        smoothingPeriod = smoothingPeriod_;"""),
    ("""    function drippable() public view returns (uint256) {
        uint256 elapsed = block.timestamp - lastDripAt;
        uint256 cap = maxCatchupSeconds;
        if (elapsed > cap) elapsed = cap;
        uint256 allowed = elapsed * dripRatePerSecond;
        uint256 bal = IERC20Min(imd).balanceOf(address(this));
        return allowed < bal ? allowed : bal;
    }""", """    /// PondPad: `buffer * min(elapsed, maxCatchup) / smoothingPeriod`; after a full catch-up window, at least
    /// `min(minDripAmount, buffer / 7)` so small buffers keep draining, and all of a remainder under one $PONDPAD.
    /// One drip never releases more than 1/7 of the buffer otherwise (audit R3-A3-1: the floor used to be
    /// `min(buffer, minDripAmount)`, the whole of a small buffer). Nothing while the vault is closed for rewards.
    function drippable() public view returns (uint256) {
        (bool open, uint256 elapsed) = _elapsed();
        if (!open) return 0;
        uint256 cap = maxCatchupSeconds;
        bool fullWindow = elapsed >= cap;
        if (fullWindow) elapsed = cap;
        uint256 bal = IERC20Min(imd).balanceOf(address(this));
        uint256 allowed = (bal * elapsed) / smoothingPeriod;
        if (fullWindow) {
            uint256 seventh = bal / CATCHUP_DIVISOR;
            uint256 floor = minDripAmount < seventh ? minDripAmount : seventh;
            if (allowed < floor) allowed = floor;
            if (bal - allowed < DUST_SWEEP) allowed = bal; // a remainder under one $PONDPAD goes in full
        }
        return allowed < bal ? allowed : bal;
    }

    /// @dev PondPad: a drip is due when it releases at least `minDripAmount`, or when a full catch-up window has
    /// passed and it sweeps a remainder smaller than that.
    function _dripDue(uint256 amount) internal view returns (bool) {
        if (amount == 0) return false;
        if (amount >= minDripAmount) return true;
        (, uint256 elapsed) = _elapsed();
        return elapsed >= maxCatchupSeconds;
    }

    /// @dev PondPad (audit R2-A3-3): time counts from the last drip or from when the vault last opened for
    /// rewards, whichever is later, so time without stakers is forfeited, not banked for the first one.
    function _elapsed() internal view returns (bool open, uint256 elapsed) {
        uint256 since = IRewardVault(vault).rewardsOpenSince();
        if (since == 0) return (false, 0);
        uint256 from = lastDripAt > since ? lastDripAt : since;
        return (true, block.timestamp - from);
    }"""),
    ("""        return drippable() >= minDripAmount && IERC20Min(vault).totalSupply() != 0;""", """        return _dripDue(drippable()); // PondPad: nothing is drippable while the vault is closed"""),
    ("""        if (IERC20Min(vault).totalSupply() == 0) revert VaultEmpty();""", """        if (IRewardVault(vault).rewardsOpenSince() == 0) revert VaultEmpty();"""),
    ("""    /// replay stranded 14% of the rewards this way. Rewards wait here until someone stakes.""", """    /// replay stranded 14% of the rewards this way. Rewards wait here until someone stakes.
    /// @dev PondPad (audits R1-A3-1, R2-A3-1): "empty" means the vault is closed for rewards (`rewardsOpenSince`
    /// is 0: less than one whole $PONDPAD or 1e18 shares staked), not zero shares. The vault has 1e6 virtual
    /// shares (6-decimal offset), so a 1-wei first stake (1e6 shares) would leave half of every drip with the
    /// virtual shares; with 1e18 real shares they get at most 1e-12. The vault counts its own assets, so a
    /// transfer into the empty vault can no longer push the share count out of reach."""),
    ("""        uint256 amount = drippable();
        if (amount < minDripAmount) revert BelowMinDrip();
        lastDripAt = block.timestamp;

        paidKeeper = keeperReward;""", """        uint256 amount = drippable();
        if (!_dripDue(amount)) revert BelowMinDrip();
        lastDripAt = block.timestamp;

        // PondPad: no tip on a small-remainder sweep, so the keeper can never take most of it.
        paidKeeper = amount >= minDripAmount ? keeperReward : 0;"""),
    ("""        if (toVault != 0) imd.safeTransfer(vault, toVault);""", """        if (toVault != 0) {
            imd.safeTransfer(vault, toVault);
            IRewardVault(vault).syncRewards(); // PondPad (R2-A3-1): the vault counts what it receives
        }"""),
    ("""    function setVault(address vault_) external onlyOwner {
        if (vault_ == address(0)) revert ZeroAddress();
        vault = vault_;
        emit VaultSet(vault_);
    }

    function setDripRate(uint256 dripRatePerSecond_) external onlyOwner {
        if (dripRatePerSecond_ > MAX_RATE) revert RateTooHigh();
        dripRatePerSecond = dripRatePerSecond_;
        emit DripRateSet(dripRatePerSecond_);
    }""", """    /// @notice PondPad: how long the waiting rewards take to pay out (1-30 days).
    function setSmoothingPeriod(uint256 smoothingPeriod_) external onlyOwnerActive {
        if (smoothingPeriod_ < MIN_SMOOTHING || smoothingPeriod_ > MAX_SMOOTHING) revert InvalidSmoothing();
        if (maxCatchupSeconds > smoothingPeriod_ / CATCHUP_DIVISOR) revert CatchupTooHigh();
        smoothingPeriod = smoothingPeriod_;
        emit SmoothingPeriodSet(smoothingPeriod_);
    }"""),
    ("""    function setMaxCatchup(uint256 maxCatchupSeconds_) external onlyOwner {
        if (maxCatchupSeconds_ == 0 || maxCatchupSeconds_ > MAX_CATCHUP) revert CatchupTooHigh();""", """    function setMaxCatchup(uint256 maxCatchupSeconds_) external onlyOwnerActive {
        if (maxCatchupSeconds_ < MIN_CATCHUP) revert CatchupTooLow();
        if (maxCatchupSeconds_ > smoothingPeriod / CATCHUP_DIVISOR) revert CatchupTooHigh();"""),
    ('function setKeeperReward(uint256 keeperReward_) external onlyOwner {', 'function setKeeperReward(uint256 keeperReward_) external onlyOwnerActive {'),
    ('function setMinDripAmount(uint256 minDripAmount_) external onlyOwner {', 'function setMinDripAmount(uint256 minDripAmount_) external onlyOwnerActive {'),
    ("""        if (keeperReward > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        minDripAmount = minDripAmount_;""", """        if (minDripAmount_ > MAX_MIN_DRIP) revert MinDripTooHigh(); // PondPad (R1-A3-8)
        if (keeperReward > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        minDripAmount = minDripAmount_;"""),
    ("""    /// @notice The staking vault that receives the stream. A plain transfer raises its `totalAssets`.
    /// PondPad: immutable.""", """    /// @notice The staking vault that receives the stream. PondPad: immutable; a drip is a transfer followed by
    /// the vault's `syncRewards()` (a plain transfer alone no longer raises its `totalAssets`, R2-A3-1)."""),
    ("""interface IERC20Min {
    function balanceOf(address account) external view returns (uint256);
    function totalSupply() external view returns (uint256);
}""", """interface IERC20Min {
    function balanceOf(address account) external view returns (uint256);
    function totalSupply() external view returns (uint256);
}

/// @dev PondPad: the sPONDPAD vault's reward intake (audits R2-A3-1, R2-A3-3).
interface IRewardVault {
    function rewardsOpenSince() external view returns (uint256);
    function syncRewards() external returns (uint256);
}"""),
    ("""    /// @notice Owner sweeps a balance — including the reward IMD buffer — to `to`. Trusted power,
    /// removed on `renounceOwnership()`.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwner {""", """    /// @notice Owner sweeps a stray balance to `to`. PondPad: never the reward buffer.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == imd) revert CannotRescueRewards();"""),
    ('function rescueETH(address to, uint256 amount) external onlyOwner {', 'function rescueETH(address to, uint256 amount) external onlyOwnerActive {'),
    ("""        if (dripRatePerSecond == 0 || vault == address(0)) revert RenounceWouldFreeze();
        if (minDripAmount > dripRatePerSecond * maxCatchupSeconds) revert RenounceWouldFreeze();""", """        // PondPad: the self-adjusting release always drains (smoothingPeriod is bounded, small buffers sweep).
        if (vault == address(0)) revert RenounceWouldFreeze();"""),
    # PondPad (audits R3-A2-2 / R3-A4-4): the owner (the 48 h timelock) is fixed; the powers end at powersExpireAt.
    ('import {Ownable} from "solady/auth/Ownable.sol";', 'import {FixedOwnable} from "./FixedOwnable.sol";'),
    ('contract RewardDripper is Ownable {', 'contract RewardDripper is FixedOwnable {'),
    ("""    /// @dev Don't let ownership be dropped into a config that can never drain the buffer to stakers:
    /// rate 0 (no stream) or a `minDripAmount` above the per-call ceiling (`drip()` could never fire)
    /// would strand rewards here forever with no owner left to fix it.
    function renounceOwnership() public payable override onlyOwner {
        // PondPad: the self-adjusting release always drains (smoothingPeriod is bounded, small buffers sweep).
        if (vault == address(0)) revert RenounceWouldFreeze();
        super.renounceOwnership();
    }""", """    // PondPad (audits R3-A2-2 / R3-A4-4): no renounce, transfer or handover (FixedOwnable); the powers end at
    // `powersExpireAt`, and the self-adjusting release always drains."""),
], ['external onlyOwner {', 'setVault', 'dripRatePerSecond', 'MAX_RATE', 'is Ownable'])
print('ok')
