// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {FixedOwnable} from "./FixedOwnable.sol";
import {SafeTransferLib} from "solady/utils/SafeTransferLib.sol";

interface IERC20Min {
    function balanceOf(address account) external view returns (uint256);
}

/// @dev PondPad: the sPONDPAD vault's reward intake (audits R2-A3-1, R2-A3-3).
interface IRewardVault {
    function rewardsOpenSince() external view returns (uint256);
    function syncRewards() external returns (uint256);
}

/// @notice PondPad: a fork of POOL4's RewardDripper (MIT, 0xe6D3De6daEAf327fCA42745f1998FcD989e00884; original in
/// `upstream/RewardDripper.sol`, regenerated by `upstream/make_staking.py`). The streamed asset is $PONDPAD (the
/// variable keeps its upstream name `imd`). Inflows: 15% of the market's trims, PadBuyer's purchases and the
/// stakers' share of $PONDPAD fees. Changes:
///   - Self-adjusting release (D-44): instead of a fixed `dripRatePerSecond`, each drip releases
///     `buffer * elapsed / smoothingPeriod` (elapsed capped at `maxCatchupSeconds`), so the waiting rewards pay out
///     smoothly over about `smoothingPeriod` (default 7 days: ~0.6% of the buffer per hour) whatever the volume or
///     price. After a full catch-up window, a drip releases at least `min(minDripAmount, buffer / 7)` (audit
///     R3-A3-1), so small buffers keep draining without breaking the 1/7 bound; one below `minDripAmount` pays no
///     keeper tip, and a remainder under one whole $PONDPAD is swept in full.
///   - Drips wait until the vault is open for rewards (at least one whole $PONDPAD staked, audit R1-A3-1 /
///     R2-A3-1); time the vault was closed is forfeited, not banked (R2-A3-3). Each drip is taken in by the vault's
///     `syncRewards()`.
///   - Bounds (audit R2-A3-2, R2-A3-4, R1-A3-8, R3-A3-1): `1 hour <= maxCatchupSeconds <= smoothingPeriod / 7` and
///     the floor capped at 1/7 of the buffer, so one drip releases at most 1/7 of the buffer (or a remainder under
///     one $PONDPAD) and the floor fires at most hourly; `minDripAmount <= 100,000 $PONDPAD`.
///   - D-42: the vault is fixed at deploy (no `setVault`); `rescueERC20` can never touch the reward buffer, nor
///     sPONDPAD (audit R5-A3-2); all owner powers expire at `powersExpireAt` (12 months after launch).
/// Upstream doc follows; its "rate" wording describes the original fixed-rate formula.
///
/// Smooths the market's lumpy 10% reward share into a bounded stream for the staking vault.
///
/// @dev The `CappedBurnHook` accrues its reward share and, on the permissionless `settleClaims()`,
/// pushes the WHOLE accumulated buffer to its (immutable) `rewardsRecipient` in one shot. Point that
/// `rewardsRecipient` at this contract and the lump lands here instead of the vault. This contract
/// then releases IMD to the vault at a bounded rate, so the vault's share price only ever steps up in
/// small increments — leaving nothing large enough for a just-in-time staker to farm.
///
/// The guarantee: a single `drip()` transfers at most `dripRatePerSecond * maxCatchupSeconds` (the
/// per-call lump ceiling), and the sustained throughput never exceeds `dripRatePerSecond` (the rate
/// ceiling). Idle time beyond `maxCatchupSeconds` is forfeited, not banked — so a long gap followed by
/// one `drip()` can NEVER dump the accumulated buffer at once; a large buffer only drains through many
/// small drips across many blocks. Size the knobs so `dripRatePerSecond * maxCatchupSeconds` stays
/// under ~0.1–0.5% of vault TVL.
///
/// `drip()` is permissionless and pays its caller `keeperReward` IMD (out of the released amount) so a
/// keeper/bot is compensated for gas. To keep that fee a tiny fraction of each drip, `drip()` only
/// fires once at least `minDripAmount` is releasable (`keeperReward <= minDripAmount` is enforced, so
/// the keeper can never take more than the drip). PondPad (audit R5-A3-5; this replaces the upstream sentence on
/// owner powers, which promised a buffer rescue and a renounce): both are tuned by the owner (the 48 h timelock)
/// within bounds, as are the smoothing period and the catch-up window; the owner can rescue only stray tokens,
/// never the reward buffer or sPONDPAD; ownership can't be renounced, transferred or handed over (FixedOwnable);
/// and every power ends at `powersExpireAt`, which leaves an autonomous stream.
contract RewardDripper is FixedOwnable {
    using SafeTransferLib for address;

    /// @notice The reward asset that is streamed to the vault (IMD).
    address public immutable imd;

    /// @notice The staking vault that receives the stream. PondPad: immutable; a drip is a transfer followed by
    /// the vault's `syncRewards()` (a plain transfer alone no longer raises its `totalAssets`, R2-A3-1).
    address public immutable vault;
    /// @notice PondPad: the waiting rewards are released over about this long (share per second = 1 / period).
    uint256 public smoothingPeriod;
    /// @notice Cap on the elapsed time a single `drip()` may account for — bounds the per-call lump.
    uint256 public maxCatchupSeconds;
    /// @notice Timestamp the release clock was last advanced.
    uint256 public lastDripAt;
    /// @notice IMD paid to whoever calls `drip()`, taken out of the released amount (gas compensation).
    uint256 public keeperReward;
    /// @notice `drip()` only fires once at least this much is releasable — keeps `keeperReward` a small
    /// fraction of each drip and stops keepers spamming dust drips to farm the fee.
    uint256 public minDripAmount;

    uint256 public constant MIN_SMOOTHING = 1 days; // PondPad
    uint256 public constant MAX_SMOOTHING = 30 days; // PondPad
    /// @notice PondPad (audit R2-A3-4): a catch-up window of at least an hour, so the `minDripAmount` floor can't
    /// fire every second.
    uint256 public constant MIN_CATCHUP = 1 hours;
    /// @notice PondPad (audit R2-A3-2): `maxCatchupSeconds <= smoothingPeriod / 7`: one drip releases at most 1/7
    /// of the buffer.
    uint256 public constant CATCHUP_DIVISOR = 7;
    /// @notice PondPad (audit R1-A3-8): a larger floor could stall the stream, then release the buffer at once.
    uint256 public constant MAX_MIN_DRIP = 100_000e18;
    /// @notice PondPad (audit R3-A3-1): after a full window, a remainder under this is swept in full, so a buffer
    /// draining at 1/7 per window still empties.
    uint256 public constant DUST_SWEEP = 1e18;
    /// @dev The keeper reward may be at most `minDripAmount / KEEPER_REWARD_DIVISOR` (≤ 1% of a drip),
    /// so the vault always receives the dominant share — even at the smallest drip. Equality of the two
    /// knobs (which would let a keeper take a whole drip) is thereby impossible.
    uint256 internal constant KEEPER_REWARD_DIVISOR = 100;

    event Dripped(uint256 toVault, uint256 keeperReward, address indexed keeper);
    event SmoothingPeriodSet(uint256 smoothingPeriod);
    event MaxCatchupSet(uint256 maxCatchupSeconds);
    event KeeperRewardSet(uint256 keeperReward);
    event MinDripAmountSet(uint256 minDripAmount);
    event EmergencyRescue(address indexed token, address indexed to, uint256 amount);

    error ZeroAddress();
    error InvalidSmoothing();
    error CatchupTooLow();
    error MinDripTooHigh();
    error CatchupTooHigh();
    error KeeperRewardExceedsMin();
    error BelowMinDrip();
    error VaultEmpty();
    error CannotRescueRewards();

    // ─────────────────────────────── PondPad: limited, expiring powers (D-42) ───────────────────────────────

    /// @notice PondPad: every owner power stops working at this time (12 months after launch), as if renounced.
    uint256 public immutable powersExpireAt;

    error PowersExpired();

    modifier onlyOwnerActive() {
        _checkOwner();
        if (block.timestamp >= powersExpireAt) revert PowersExpired();
        _;
    }

    constructor(
        address imd_,
        address vault_,
        address owner_,
        uint256 smoothingPeriod_,
        uint256 maxCatchupSeconds_,
        uint256 keeperReward_,
        uint256 minDripAmount_,
        uint256 powersExpireAt_
    ) {
        if (imd_ == address(0) || vault_ == address(0) || owner_ == address(0)) revert ZeroAddress();
        if (smoothingPeriod_ < MIN_SMOOTHING || smoothingPeriod_ > MAX_SMOOTHING) revert InvalidSmoothing();
        if (maxCatchupSeconds_ < MIN_CATCHUP) revert CatchupTooLow();
        if (maxCatchupSeconds_ > smoothingPeriod_ / CATCHUP_DIVISOR) revert CatchupTooHigh();
        if (minDripAmount_ > MAX_MIN_DRIP) revert MinDripTooHigh();
        if (keeperReward_ > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        powersExpireAt = powersExpireAt_;
        imd = imd_;
        vault = vault_;
        smoothingPeriod = smoothingPeriod_;
        maxCatchupSeconds = maxCatchupSeconds_;
        keeperReward = keeperReward_;
        minDripAmount = minDripAmount_;
        lastDripAt = block.timestamp;
        _initializeOwner(owner_);
    }

    // ─────────────────────────────── Stream ───────────────────────────────

    /// @notice IMD releasable right now: `min(rate * min(elapsed, maxCatchup), balance)`. This is the
    /// total that leaves the dripper on the next `drip()` (vault share + keeper reward combined).
    /// PondPad: `buffer * min(elapsed, maxCatchup) / smoothingPeriod`; after a full catch-up window, at least
    /// `min(minDripAmount, buffer / 7)` so small buffers keep draining, and all of a remainder under one $PONDPAD.
    /// One drip never releases more than 1/7 of the buffer otherwise (audit R3-A3-1: the floor used to be
    /// `min(buffer, minDripAmount)`, the whole of a small buffer). Nothing while the vault is closed for rewards.
    function drippable() public view returns (uint256) {
        (bool open, uint256 elapsed) = _elapsed();
        if (!open) return 0;
        uint256 cap = maxCatchupSeconds;
        bool fullWindow = elapsed >= cap;
        if (fullWindow) elapsed = cap;
        uint256 bal = IERC20Min(imd).balanceOf(address(this));
        uint256 allowed = (bal * elapsed) / smoothingPeriod;
        if (fullWindow) {
            uint256 seventh = bal / CATCHUP_DIVISOR;
            uint256 floor = minDripAmount < seventh ? minDripAmount : seventh;
            if (allowed < floor) allowed = floor;
            if (bal - allowed < DUST_SWEEP) allowed = bal; // a remainder under one $PONDPAD goes in full
        }
        return allowed < bal ? allowed : bal;
    }

    /// @dev PondPad: a drip is due when it releases at least `minDripAmount`, or when a full catch-up window has
    /// passed and it sweeps a remainder smaller than that.
    function _dripDue(uint256 amount) internal view returns (bool) {
        if (amount == 0) return false;
        if (amount >= minDripAmount) return true;
        (, uint256 elapsed) = _elapsed();
        return elapsed >= maxCatchupSeconds;
    }

    /// @dev PondPad (audit R2-A3-3): time counts from the last drip or from when the vault last opened for
    /// rewards, whichever is later, so time without stakers is forfeited, not banked for the first one.
    function _elapsed() internal view returns (bool open, uint256 elapsed) {
        uint256 since = IRewardVault(vault).rewardsOpenSince();
        if (since == 0) return (false, 0);
        uint256 from = lastDripAt > since ? lastDripAt : since;
        return (true, block.timestamp - from);
    }

    /// @notice Whether `drip()` would succeed right now (releasable has reached `minDripAmount` and the
    /// vault has stakers to receive it).
    function canDrip() external view returns (bool) {
        return _dripDue(drippable()); // PondPad: nothing is drippable while the vault is closed
    }

    /// @notice Permissionless: push the releasable IMD to the vault, pay the caller `keeperReward`, and
    /// advance the clock. Reverts until at least `minDripAmount` is releasable.
    /// @dev The clock resets to `now` even when the balance capped the release, so unused idle time is
    /// forfeited rather than banked into a future burst. `keeperReward <= minDripAmount <= amount`, so
    /// the vault share can't underflow.
    /// @dev Never streams into a vault with no shares: assets that land in an empty ERC-4626 are captured
    /// by its virtual shares (nobody can redeem them) and leave the first real depositor with a tiny share
    /// count, so a slice of every later drip keeps leaking to those virtual shares. A 15-day mainnet-fork
    /// replay stranded 14% of the rewards this way. Rewards wait here until someone stakes.
    /// @dev PondPad (audits R1-A3-1, R2-A3-1): "empty" means the vault is closed for rewards (`rewardsOpenSince`
    /// is 0: less than one whole $PONDPAD or 1e18 shares staked), not zero shares. The vault has 1e6 virtual
    /// shares (6-decimal offset), so a 1-wei first stake (1e6 shares) would leave half of every drip with the
    /// virtual shares; with 1e18 real shares they get at most 1e-12. The vault counts its own assets, so a
    /// transfer into the empty vault can no longer push the share count out of reach.
    function drip() external returns (uint256 toVault, uint256 paidKeeper) {
        if (IRewardVault(vault).rewardsOpenSince() == 0) revert VaultEmpty();
        uint256 amount = drippable();
        if (!_dripDue(amount)) revert BelowMinDrip();
        lastDripAt = block.timestamp;

        // PondPad: no tip on a small-remainder sweep, so the keeper can never take most of it.
        paidKeeper = amount >= minDripAmount ? keeperReward : 0;
        toVault = amount - paidKeeper;
        if (toVault != 0) {
            imd.safeTransfer(vault, toVault);
            IRewardVault(vault).syncRewards(); // PondPad (R2-A3-1): the vault counts what it receives
        }
        if (paidKeeper != 0) imd.safeTransfer(msg.sender, paidKeeper);
        emit Dripped(toVault, paidKeeper, msg.sender);
    }

    // ─────────────────────────────── Owner config ───────────────────────────────

    /// @notice PondPad: how long the waiting rewards take to pay out (1-30 days).
    function setSmoothingPeriod(uint256 smoothingPeriod_) external onlyOwnerActive {
        if (smoothingPeriod_ < MIN_SMOOTHING || smoothingPeriod_ > MAX_SMOOTHING) revert InvalidSmoothing();
        if (maxCatchupSeconds > smoothingPeriod_ / CATCHUP_DIVISOR) revert CatchupTooHigh();
        smoothingPeriod = smoothingPeriod_;
        emit SmoothingPeriodSet(smoothingPeriod_);
    }

    function setMaxCatchup(uint256 maxCatchupSeconds_) external onlyOwnerActive {
        if (maxCatchupSeconds_ < MIN_CATCHUP) revert CatchupTooLow();
        if (maxCatchupSeconds_ > smoothingPeriod / CATCHUP_DIVISOR) revert CatchupTooHigh();
        maxCatchupSeconds = maxCatchupSeconds_;
        emit MaxCatchupSet(maxCatchupSeconds_);
    }

    function setKeeperReward(uint256 keeperReward_) external onlyOwnerActive {
        if (keeperReward_ > minDripAmount / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        keeperReward = keeperReward_;
        emit KeeperRewardSet(keeperReward_);
    }

    function setMinDripAmount(uint256 minDripAmount_) external onlyOwnerActive {
        if (minDripAmount_ > MAX_MIN_DRIP) revert MinDripTooHigh(); // PondPad (R1-A3-8)
        if (keeperReward > minDripAmount_ / KEEPER_REWARD_DIVISOR) revert KeeperRewardExceedsMin();
        minDripAmount = minDripAmount_;
        emit MinDripAmountSet(minDripAmount_);
    }

    // ─────────────────────────────── Emergency ───────────────────────────────

    /// @notice Owner sweeps a stray balance to `to`. PondPad: never the reward buffer, and never sPONDPAD, whose
    /// shares stand for staked $PONDPAD (audit R5-A3-2).
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == imd || token == vault) revert CannotRescueRewards();
        token.safeTransfer(to, amount);
        emit EmergencyRescue(token, to, amount);
    }

    function rescueETH(address to, uint256 amount) external onlyOwnerActive {
        to.safeTransferETH(amount);
        emit EmergencyRescue(address(0), to, amount);
    }

    // PondPad (audits R3-A2-2 / R3-A4-4): no renounce, transfer or handover (FixedOwnable); the powers end at
    // `powersExpireAt`, and the self-adjusting release always drains.
}
