// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {ERC4626} from "solady/tokens/ERC4626.sol";
import {FixedOwnable} from "./FixedOwnable.sol";
import {SafeTransferLib} from "solady/utils/SafeTransferLib.sol";

/// @notice PondPad: sPONDPAD, a fork of POOL4's StakedIMD (MIT, 0x9efa934d9fad4ae28c998a40195646b965a97247; original in
/// `upstream/StakedIMD.sol`, regenerated by `upstream/make_staking.py`). Asset is $PONDPAD instead of IMD. Owner
/// powers are narrowed (D-42): the owner (7-day timelock) can pause for at most 3 days at a time, with 4 days
/// unpaused between pauses; `rescueERC20` can never touch the staked $PONDPAD; and every power expires
/// `powersExpireAt` (12 months after launch). Audit fixes: only the shares that arrived this block are held
/// (R1-A3-2); `totalAssets` is the vault's own count, not its raw balance, so a transfer into an empty vault can't
/// move the share price, and rewards are taken in only while at least one whole $PONDPAD is staked (R2-A3-1).
/// Upstream doc follows ("IMD" = the asset).
///
/// Single-asset, autocompounding IMD staking vault. Stake IMD, receive `sIMD` shares; as
/// reward IMD is dripped into this contract (e.g. the market's reward share), `totalAssets` rises and
/// every share becomes worth more IMD. No separate reward token and no claim step — you simply redeem
/// more IMD than you deposited. Anti-JIT has two layers: the RewardDripper streams rewards in small,
/// frequent steps, and a one-block hold here blocks a same-block deposit→redeem, which together defeat
/// the atomic (flash-loanable) `deposit → drip → redeem` sandwich that could otherwise farm a drip.
///
/// @dev A plain ERC4626 (deposit/withdraw any time bar the one-block hold) plus a renounceable owner.
/// Solady's virtual shares (on by default) plus a decimals offset neutralise the first-depositor
/// inflation attack. Assumes an 18-decimal asset (IMD is 18).
///
/// EMERGENCY POWERS (all held by the owner, all removed the instant `renounceOwnership()` is called):
///   - `setPaused(true)` — a full stop: every deposit, mint, withdraw and redeem reverts.
///   - `rescueERC20` / `rescueETH` — sweep ANY balance, INCLUDING the staked IMD, to a chosen address.
///
/// The rescue functions can move stakers' IMD, so until ownership is renounced the owner is a trusted
/// party (this is a deliberate "move funds to safety in a worst case" hatch, not a trustless design).
/// Renouncing drops both powers permanently and leaves an immutable, trustless ERC4626. To avoid
/// bricking the vault, ownership cannot be renounced while paused — unpause first.
contract StakedPONDPAD is ERC4626, FixedOwnable {
    using SafeTransferLib for address;

    address internal immutable _asset;

    /// @notice PondPad: a pause lasts until this time (at most `MAX_PAUSE` after it starts).
    uint256 public pausedUntil;
    /// @notice PondPad: a new pause may start only from this time (`PAUSE_COOLDOWN` after the last one ended).
    uint256 public nextPauseAllowedAt;
    uint256 public constant MAX_PAUSE = 3 days;
    uint256 public constant PAUSE_COOLDOWN = 4 days;

    // ─────────────────────────────── PondPad: limited, expiring powers (D-42) ───────────────────────────────

    /// @notice PondPad: every owner power stops working at this time (12 months after launch), as if renounced.
    uint256 public immutable powersExpireAt;

    error PowersExpired();

    modifier onlyOwnerActive() {
        _checkOwner();
        if (block.timestamp >= powersExpireAt) revert PowersExpired();
        _;
    }

    /// @notice Block of each holder's most recent share-increasing action, for the one-block hold.
    mapping(address => uint256) public lastDepositBlock;
    /// @notice PondPad (audit R1-A3-2): shares that reached each holder in block `lastDepositBlock`; only these
    /// are held, not the whole balance.
    mapping(address => uint256) public heldShares;

    /// @notice PondPad (audit R2-A3-1): the staked $PONDPAD the vault counts (`totalAssets`). Upstream counted its
    /// raw balance, so a dust transfer into the empty vault fixed a share price at which no stake could ever reach
    /// the dripper's minimum. Deposits add, withdrawals subtract, and $PONDPAD that arrives by plain transfer (the
    /// dripper's drips) counts only once `syncRewards()` takes it in, which works only while rewards are open.
    uint256 public trackedAssets;
    /// @notice PondPad: rewards are open while at least this many shares AND this much $PONDPAD are staked. One whole
    /// $PONDPAD at the starting price; the 1e6 virtual shares then get at most 1e-12 of a drip (R1-A3-1).
    uint256 public constant MIN_REWARD_SHARES = 1e18;
    uint256 public constant MIN_REWARD_ASSETS = 1e18;
    /// @notice PondPad (audit R2-A3-3): when rewards last opened (0 while closed). The dripper releases nothing
    /// for time the vault was closed, so the first staker can't collect a window banked before it.
    uint256 public rewardsOpenSince;

    event PauseSet(bool paused);
    event EmergencyRescue(address indexed token, address indexed to, uint256 amount);

    error EnforcedPause();
    error RenounceWhilePaused();
    error SameBlockRedeem();
    error CannotRescueStake();
    error PauseCooldown();
    error RewardsClosed();

    event RewardsSynced(uint256 amount, uint256 trackedAssets);

    constructor(address asset_, address owner_, uint256 powersExpireAt_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        powersExpireAt = powersExpireAt_;
        _initializeOwner(owner_);
    }

    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. PondPad: time-limited.
    function paused() public view returns (bool) {
        return block.timestamp < pausedUntil;
    }

    // ─────────────────────────────── ERC4626 config ───────────────────────────────

    function asset() public view override returns (address) {
        return _asset;
    }

    function name() public pure override returns (string memory) {
        return "Staked PondPad";
    }

    function symbol() public pure override returns (string memory) {
        return "sPONDPAD";
    }

    /// @dev On top of Solady's virtual shares, a non-zero offset makes the first-depositor inflation
    /// attack economically hopeless (the attacker must donate ~1e6x more than any victim deposit).
    function _decimalsOffset() internal pure override returns (uint8) {
        return 6;
    }

    /// @dev PondPad (audit R2-A3-1): the vault's own count, never its raw balance. With no shares left the price
    /// restarts (any rounding residue goes to the next staker).
    function totalAssets() public view override returns (uint256) {
        return totalSupply() == 0 ? 0 : trackedAssets;
    }

    /// @notice PondPad (audit R2-A3-1): takes $PONDPAD that reached the vault by plain transfer (the dripper's drips,
    /// or a stray transfer) into `totalAssets`, raising every share's value. Permissionless, and only while rewards
    /// are open, so nothing sent to an empty or dust-only vault can ever move the share price.
    function syncRewards() external returns (uint256 amount) {
        if (rewardsOpenSince == 0) revert RewardsClosed();
        uint256 bal = SafeTransferLib.balanceOf(_asset, address(this));
        amount = bal - trackedAssets;
        trackedAssets = bal;
        emit RewardsSynced(amount, bal);
    }

    /// @dev PondPad (audit R2-A3-3): opens rewards when the stake first reaches the minimum, closes them below it.
    function _updateRewardsOpen() internal {
        if (totalSupply() < MIN_REWARD_SHARES || trackedAssets < MIN_REWARD_ASSETS) rewardsOpenSince = 0;
        else if (rewardsOpenSince == 0) rewardsOpenSince = block.timestamp;
    }

    // ─────────────────────────────── Pause ───────────────────────────────

    modifier whenNotPaused() {
        if (paused()) revert EnforcedPause();
        _;
    }

    /// @dev Both funnels revert before any token movement, so a paused vault changes no balances. The
    /// one-block hold (record on the way in, block same-block exit) breaks the atomic
    /// deposit→drip→redeem sandwich that would otherwise let a flash-loaned position JIT-farm a reward
    /// drip; it forces any would-be farmer onto real capital held across a block, not free flash-loaned
    /// capital, and leaves genuine long-term staking untouched.
    function _deposit(address by, address to, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        // The hold stamp lives in `_beforeTokenTransfer` (fired by the mint below), NOT here: keying it on
        // the deposit `to` let a third party stamp any address for free (griefing) and let a depositor shed
        // it by transferring shares to a fresh account (JIT bypass). See _beforeTokenTransfer.
        super._deposit(by, to, assets, shares);
        trackedAssets += assets; // PondPad (R2-A3-1)
        _updateRewardsOpen();
    }

    function _withdraw(address by, address to, address owner, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        if (shares > _unheldShares(owner)) revert SameBlockRedeem();
        trackedAssets -= assets; // PondPad (R2-A3-1)
        super._withdraw(by, to, owner, assets, shares);
        _updateRewardsOpen();
    }

    /// @dev PondPad (audit R1-A3-2): upstream held the holder's WHOLE balance for the block after any share
    /// arrived, so anyone could block a staker's exit with `deposit(1 wei, victim)` or a 1-share transfer,
    /// every Ethereum block (D-65). Here only the shares that arrived in the current block are held: a mint
    /// holds the minted shares; a transfer moves the sender's unheld shares first and carries any held ones
    /// with it. A flash-loaned deposit is still fully held wherever it goes; stranger dust holds only the dust.
    function _heldShares(address owner) internal view returns (uint256) {
        return lastDepositBlock[owner] == block.number ? heldShares[owner] : 0;
    }

    function _unheldShares(address owner) internal view returns (uint256) {
        uint256 bal = balanceOf(owner);
        uint256 held = _heldShares(owner);
        return bal > held ? bal - held : 0;
    }

    function _hold(address to, uint256 shares) internal {
        if (lastDepositBlock[to] != block.number) {
            lastDepositBlock[to] = block.number;
            heldShares[to] = shares;
        } else {
            heldShares[to] += shares;
        }
    }

    /// @dev Upstream: the one-block anti-JIT hold must travel WITH the shares — otherwise a depositor sheds it by
    /// transferring shares to a never-stamped address and redeems there the same block (the flash-loanable
    /// deposit→drip→redeem bypass) — while a third party must not be able to stamp a hold on an account for
    /// free (a `deposit(0, victim)` / dust-transfer withdrawal grief). So: a positive mint stamps the new
    /// holder; a positive transfer carries the sender's hold forward (never lowering the recipient's);
    /// zero-amount moves and burns stamp nothing.
    function _beforeTokenTransfer(address from, address to, uint256 amount) internal override {
        // PondPad (audit R3-A3-5): burns and transfers to address(0) also go through the bookkeeping, so the sender's
        // held count never stays above its balance (a redeem only burns unheld shares, so it changes nothing there).
        if (amount == 0) return;
        if (from == address(0)) {
            _hold(to, amount); // mint (deposit): the new shares are held
        } else {
            // transfer: unheld shares leave first; any held part travels with the shares (none to address(0))
            uint256 bal = balanceOf(from);
            if (amount > bal) return; // Solady then reverts InsufficientBalance() (audit R2-A3-5)
            uint256 held = _heldShares(from);
            uint256 unheld = bal - held;
            if (amount > unheld) {
                uint256 moved = amount - unheld;
                heldShares[from] = held - moved;
                if (to != address(0)) _hold(to, moved);
            }
        }
    }

    // ─────────────────────────────── ERC4626 max* (pause-aware) ───────────────────────────────

    /// @dev While paused the funnels revert, so the max* views must report 0 (ERC4626 requires them to
    /// never report an amount that would revert).
    function maxDeposit(address to) public view override returns (uint256) {
        return paused() ? 0 : super.maxDeposit(to);
    }

    function maxMint(address to) public view override returns (uint256) {
        return paused() ? 0 : super.maxMint(to);
    }

    function maxWithdraw(address owner) public view override returns (uint256) {
        if (paused()) return 0;
        return convertToAssets(_unheldShares(owner)); // PondPad: held shares only (R1-A3-2)
    }

    function maxRedeem(address owner) public view override returns (uint256) {
        if (paused()) return 0;
        return _unheldShares(owner); // PondPad: held shares only (R1-A3-2)
    }

    /// @notice Owner emergency stop / resume. PondPad: a stop lasts at most 3 days and the next one can start only
    /// 4 days after it ended, so funds are never frozen for long; resuming early is always allowed.
    function setPaused(bool paused_) external onlyOwnerActive {
        if (paused_) {
            if (paused() || block.timestamp < nextPauseAllowedAt) revert PauseCooldown();
            // A pause never outlives the owner's powers (audit R1-A3-7): nobody could lift it after expiry.
            uint256 until = block.timestamp + MAX_PAUSE;
            pausedUntil = until < powersExpireAt ? until : powersExpireAt;
        } else {
            if (paused()) pausedUntil = block.timestamp;
        }
        nextPauseAllowedAt = (paused_ ? block.timestamp + MAX_PAUSE : block.timestamp) + PAUSE_COOLDOWN;
        emit PauseSet(paused_);
    }

    // ─────────────────────────────── Emergency recovery ───────────────────────────────

    /// @notice Owner sweeps a stray ERC20 balance to `to`. PondPad: never the staked asset.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == _asset) revert CannotRescueStake();
        token.safeTransfer(to, amount);
        emit EmergencyRescue(token, to, amount);
    }

    /// @notice Owner sweeps ETH force-sent to the vault (it has no payable entry points otherwise).
    function rescueETH(address to, uint256 amount) external onlyOwnerActive {
        to.safeTransferETH(amount);
        emit EmergencyRescue(address(0), to, amount);
    }

    // ─────────────────────────────── Renounce guard ───────────────────────────────

    // PondPad (audits R3-A2-2 / R3-A4-4): the owner can't renounce, transfer or hand over ownership
    // (FixedOwnable); its powers end at `powersExpireAt` instead, which can't leave the vault paused.
}
