// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {ERC4626} from "solady/tokens/ERC4626.sol";
import {Ownable} from "solady/auth/Ownable.sol";
import {SafeTransferLib} from "solady/utils/SafeTransferLib.sol";

/// @notice PondPad: sPONDPAD, a fork of POOL4's StakedIMD (MIT, 0x9efa934d9fad4ae28c998a40195646b965a97247; original in
/// `upstream/StakedIMD.sol`, regenerated by `upstream/make_staking.py`). Asset is $PONDPAD instead of IMD. Owner
/// powers are narrowed (D-42): the owner (7-day timelock) can pause for at most 3 days at a time, with 4 days
/// unpaused between pauses; `rescueERC20` can never touch the staked $PONDPAD; and every power expires
/// `powersExpireAt` (12 months after launch). Everything else is unchanged. Upstream doc follows ("IMD" = the asset).
///
/// Single-asset, autocompounding IMD staking vault. Stake IMD, receive `sIMD` shares; as
/// reward IMD is dripped into this contract (e.g. the market's reward share), `totalAssets` rises and
/// every share becomes worth more IMD. No separate reward token and no claim step — you simply redeem
/// more IMD than you deposited. Anti-JIT has two layers: the RewardDripper streams rewards in small,
/// frequent steps, and a one-block hold here blocks a same-block deposit→redeem, which together defeat
/// the atomic (flash-loanable) `deposit → drip → redeem` sandwich that could otherwise farm a drip.
///
/// @dev A plain ERC4626 (deposit/withdraw any time bar the one-block hold) plus a renounceable owner.
/// Solady's virtual shares (on by default) plus a decimals offset neutralise the first-depositor
/// inflation attack. Assumes an 18-decimal asset (IMD is 18).
///
/// EMERGENCY POWERS (all held by the owner, all removed the instant `renounceOwnership()` is called):
///   - `setPaused(true)` — a full stop: every deposit, mint, withdraw and redeem reverts.
///   - `rescueERC20` / `rescueETH` — sweep ANY balance, INCLUDING the staked IMD, to a chosen address.
///
/// The rescue functions can move stakers' IMD, so until ownership is renounced the owner is a trusted
/// party (this is a deliberate "move funds to safety in a worst case" hatch, not a trustless design).
/// Renouncing drops both powers permanently and leaves an immutable, trustless ERC4626. To avoid
/// bricking the vault, ownership cannot be renounced while paused — unpause first.
contract StakedPONDPAD is ERC4626, Ownable {
    using SafeTransferLib for address;

    address internal immutable _asset;

    /// @notice PondPad: a pause lasts until this time (at most `MAX_PAUSE` after it starts).
    uint256 public pausedUntil;
    /// @notice PondPad: a new pause may start only from this time (`PAUSE_COOLDOWN` after the last one ended).
    uint256 public nextPauseAllowedAt;
    uint256 public constant MAX_PAUSE = 3 days;
    uint256 public constant PAUSE_COOLDOWN = 4 days;

    // ─────────────────────────────── PondPad: limited, expiring powers (D-42) ───────────────────────────────

    /// @notice PondPad: every owner power stops working at this time (12 months after launch), as if renounced.
    uint256 public immutable powersExpireAt;

    error PowersExpired();

    modifier onlyOwnerActive() {
        _checkOwner();
        if (block.timestamp >= powersExpireAt) revert PowersExpired();
        _;
    }

    /// @notice Block of each holder's most recent share-increasing action, for the one-block hold.
    mapping(address => uint256) public lastDepositBlock;

    event PauseSet(bool paused);
    event EmergencyRescue(address indexed token, address indexed to, uint256 amount);

    error EnforcedPause();
    error RenounceWhilePaused();
    error SameBlockRedeem();
    error CannotRescueStake();
    error PauseCooldown();

    constructor(address asset_, address owner_, uint256 powersExpireAt_) {
        require(asset_ != address(0), "asset=0");
        require(owner_ != address(0), "owner=0");
        _asset = asset_;
        powersExpireAt = powersExpireAt_;
        _initializeOwner(owner_);
    }

    /// @notice When true, all deposits/mints/withdrawals/redemptions revert. PondPad: time-limited.
    function paused() public view returns (bool) {
        return block.timestamp < pausedUntil;
    }

    // ─────────────────────────────── ERC4626 config ───────────────────────────────

    function asset() public view override returns (address) {
        return _asset;
    }

    function name() public pure override returns (string memory) {
        return "Staked PondPad";
    }

    function symbol() public pure override returns (string memory) {
        return "sPONDPAD";
    }

    /// @dev On top of Solady's virtual shares, a non-zero offset makes the first-depositor inflation
    /// attack economically hopeless (the attacker must donate ~1e6x more than any victim deposit).
    function _decimalsOffset() internal pure override returns (uint8) {
        return 6;
    }

    // ─────────────────────────────── Pause ───────────────────────────────

    modifier whenNotPaused() {
        if (paused()) revert EnforcedPause();
        _;
    }

    /// @dev Both funnels revert before any token movement, so a paused vault changes no balances. The
    /// one-block hold (record on the way in, block same-block exit) breaks the atomic
    /// deposit→drip→redeem sandwich that would otherwise let a flash-loaned position JIT-farm a reward
    /// drip; it forces any would-be farmer onto real capital held across a block, not free flash-loaned
    /// capital, and leaves genuine long-term staking untouched.
    function _deposit(address by, address to, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        // The hold stamp lives in `_beforeTokenTransfer` (fired by the mint below), NOT here: keying it on
        // the deposit `to` let a third party stamp any address for free (griefing) and let a depositor shed
        // it by transferring shares to a fresh account (JIT bypass). See _beforeTokenTransfer.
        super._deposit(by, to, assets, shares);
    }

    function _withdraw(address by, address to, address owner, uint256 assets, uint256 shares)
        internal
        override
        whenNotPaused
    {
        if (block.number == lastDepositBlock[owner]) revert SameBlockRedeem();
        super._withdraw(by, to, owner, assets, shares);
    }

    /// @dev The one-block anti-JIT hold must travel WITH the shares — otherwise a depositor sheds it by
    /// transferring shares to a never-stamped address and redeems there the same block (the flash-loanable
    /// deposit→drip→redeem bypass) — while a third party must not be able to stamp a hold on an account for
    /// free (a `deposit(0, victim)` / dust-transfer withdrawal grief). So: a positive mint stamps the new
    /// holder; a positive transfer carries the sender's hold forward (never lowering the recipient's);
    /// zero-amount moves and burns stamp nothing.
    function _beforeTokenTransfer(address from, address to, uint256 amount) internal override {
        if (amount == 0 || to == address(0)) return;
        if (from == address(0)) {
            lastDepositBlock[to] = block.number; // mint (deposit)
        } else if (lastDepositBlock[from] > lastDepositBlock[to]) {
            lastDepositBlock[to] = lastDepositBlock[from]; // transfer inherits the sender's hold
        }
    }

    // ─────────────────────────────── ERC4626 max* (pause-aware) ───────────────────────────────

    /// @dev While paused the funnels revert, so the max* views must report 0 (ERC4626 requires them to
    /// never report an amount that would revert).
    function maxDeposit(address to) public view override returns (uint256) {
        return paused() ? 0 : super.maxDeposit(to);
    }

    function maxMint(address to) public view override returns (uint256) {
        return paused() ? 0 : super.maxMint(to);
    }

    function maxWithdraw(address owner) public view override returns (uint256) {
        if (paused() || block.number == lastDepositBlock[owner]) return 0;
        return super.maxWithdraw(owner);
    }

    function maxRedeem(address owner) public view override returns (uint256) {
        if (paused() || block.number == lastDepositBlock[owner]) return 0;
        return super.maxRedeem(owner);
    }

    /// @notice Owner emergency stop / resume. PondPad: a stop lasts at most 3 days and the next one can start only
    /// 4 days after it ended, so funds are never frozen for long; resuming early is always allowed.
    function setPaused(bool paused_) external onlyOwnerActive {
        if (paused_) {
            if (paused() || block.timestamp < nextPauseAllowedAt) revert PauseCooldown();
            pausedUntil = block.timestamp + MAX_PAUSE;
        } else {
            if (paused()) pausedUntil = block.timestamp;
        }
        nextPauseAllowedAt = (paused_ ? block.timestamp + MAX_PAUSE : block.timestamp) + PAUSE_COOLDOWN;
        emit PauseSet(paused_);
    }

    // ─────────────────────────────── Emergency recovery ───────────────────────────────

    /// @notice Owner sweeps a stray ERC20 balance to `to`. PondPad: never the staked asset.
    function rescueERC20(address token, address to, uint256 amount) external onlyOwnerActive {
        if (token == _asset) revert CannotRescueStake();
        token.safeTransfer(to, amount);
        emit EmergencyRescue(token, to, amount);
    }

    /// @notice Owner sweeps ETH force-sent to the vault (it has no payable entry points otherwise).
    function rescueETH(address to, uint256 amount) external onlyOwnerActive {
        to.safeTransferETH(amount);
        emit EmergencyRescue(address(0), to, amount);
    }

    // ─────────────────────────────── Renounce guard ───────────────────────────────

    /// @dev Block the footgun of renouncing while paused, which would freeze the vault forever.
    function renounceOwnership() public payable override onlyOwner {
        if (paused()) revert RenounceWhilePaused();
        super.renounceOwnership();
    }
}
